"""Workflow stage, checkpoint status, and failure reason constants.

These constants define the standard stages of the form automation workflow,
checkpoint status values for tracking progress, and failure reasons for
documenting why a stage failed. All values are stable uppercase strings
suitable for database storage and API responses.
"""

WORKFLOW_STAGE_ANALYSIS = "ANALYSIS"
WORKFLOW_STAGE_MAPPING = "MAPPING"
WORKFLOW_STAGE_REVIEW = "REVIEW"
WORKFLOW_STAGE_FILL = "FILL"
WORKFLOW_STAGE_APPROVAL = "APPROVAL"
WORKFLOW_STAGE_SUBMISSION = "SUBMISSION"

CHECKPOINT_SUCCESS = "SUCCESS"
CHECKPOINT_FAILED = "FAILED"
CHECKPOINT_SKIPPED = "SKIPPED"

FAILURE_ANALYSIS_FAILED = "ANALYSIS_FAILED"
FAILURE_LLM_MAPPING_FAILED = "LLM_MAPPING_FAILED"
FAILURE_REQUIRED_FIELD_MISSING = "REQUIRED_FIELD_MISSING"
FAILURE_BROWSER_FILL_FAILED = "BROWSER_FILL_FAILED"
FAILURE_SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND"
FAILURE_VALUE_VERIFICATION_FAILED = "VALUE_VERIFICATION_FAILED"
FAILURE_LOGIN_REQUIRED = "LOGIN_REQUIRED"
FAILURE_SUBMISSION_REQUIRES_APPROVAL = "SUBMISSION_REQUIRES_APPROVAL"